[tool.poetry]
name = "karenizer"
version = "0.1.0"
description = ""
authors = ["Karan Jakhar"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
